[package]
edition = "2021"
name = "offload"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
log = "0.4.20"
trace = "0.1.7"
